# Generated by Django 5.0.4 on 2024-05-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_added_date_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='default_image.png', upload_to='media/images', verbose_name='Изображение'),
        ),
    ]
